spring.application.name=HardwareStore

#spring.sql.init.mode=always
#debug=true

spring.datasource.url=jdbc:sqlserver://localhost:1433;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=hardware_shop;
spring.datasource.username=sa
spring.datasource.password=SQL
server.port=8081


